/*
 * Icon — Material Symbols Rounded, the design system's icon set.
 *
 * The font is self-hosted and SUBSET to our ~29 icons (24 KB, not the 4.6 MB
 * full font). It's variable, so FILL / weight / optical-size are set
 * per-instance via `font-variation-settings`; `opsz` tracks the pixel size for
 * optical correctness, exactly as the mockups do. Glyphs render by private-use
 * codepoint (not the letter ligature) — that's what keeps the subset tiny.
 *
 * `IconName` and the codepoint map are GENERATED by scripts/subset-icons.py.
 * To add an icon: add its name to the ICONS list there and run `npm run
 * gen:icons` (regenerates the font + iconCodepoints.ts).
 */
import type { CSSProperties } from 'react';
import { ICON_CODEPOINTS, type IconName } from './iconCodepoints';

export type { IconName };

export function Icon({
  name,
  size = 20,
  fill = false,
  weight = 400,
  className = '',
  label,
}: {
  name: IconName;
  /** Rendered glyph size in px; also drives the `opsz` axis. */
  size?: number;
  /** Solid vs outline (the design uses fill for active/emphasis states). */
  fill?: boolean;
  weight?: 300 | 400 | 500 | 600 | 700;
  className?: string;
  /** When set, the icon is announced to AT; otherwise it's decorative. */
  label?: string;
}) {
  const style: CSSProperties = {
    fontSize: size,
    fontVariationSettings: `'FILL' ${fill ? 1 : 0}, 'wght' ${weight}, 'GRAD' 0, 'opsz' ${size}`,
  };
  return (
    <span
      className={`material-symbols-rounded ${className}`}
      style={style}
      aria-hidden={label ? undefined : true}
      role={label ? 'img' : undefined}
      aria-label={label}
    >
      {ICON_CODEPOINTS[name]}
    </span>
  );
}
