// GENERATED by scripts/subset-icons.py — do not edit by hand.
// Maps each icon name to its Material Symbols private-use codepoint.
// Re-generate with `npm run gen:icons` after changing the ICONS list.

export const ICON_CODEPOINTS = {
  today: '\ue8df',
  calendar_month: '\uebcc',
  checklist: '\ue6b1',
  fitness_center: '\ueb43',
  restaurant: '\ue56c',
  monitoring: '\uf190',
  local_fire_department: '\uef55',
  play_arrow: '\ue037',
  check_circle: '\uf0be',
  close: '\ue5cd',
  add: '\ue145',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  expand_more: '\ue5cf',
  expand_less: '\ue5ce',
  refresh: '\ue5d5',
  lock: '\ue899',
  lightbulb: '\ue90f',
  offline_bolt: '\ue932',
  volume_up: '\ue050',
  volume_off: '\ue04f',
  more_horiz: '\ue5d3',
  ios_share: '\ue6b8',
  book: '\ue86e',
  timer: '\ue425',
  north_east: '\uf1e1',
  star: '\uf09a',
  arrow_downward: '\ue5db',
  arrow_forward: '\ue5c8',
} as const;

export type IconName = keyof typeof ICON_CODEPOINTS;
