#!/usr/bin/env python3
"""
Subset Material Symbols Rounded down to the icons the app actually uses.

The full variable font shipped by the `material-symbols` npm package is ~4.6 MB
(every glyph). We use a closed set of ~30 icons, so we subset by each icon's
private-use codepoint — keeping the variable FILL/wght/GRAD/opsz axes intact —
which drops it to a few tens of KB. Rendering by codepoint (not the letter
ligature) is what keeps the subset tiny: it needs neither the alphabet glyphs
nor the `liga` GSUB feature.

Outputs:
  - src/theme/fonts/material-symbols-rounded-subset.woff2  (committed)
  - src/components/iconCodepoints.ts                       (generated map + type)

Run:  npm run gen:icons   (see package.json)  — re-run whenever ICONS changes.
"""
import os
import sys
import json
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_FONT = os.path.join(ROOT, "node_modules", "material-symbols", "material-symbols-rounded.woff2")
OUT_FONT = os.path.join(ROOT, "src", "theme", "fonts", "material-symbols-rounded-subset.woff2")
OUT_TS = os.path.join(ROOT, "src", "components", "iconCodepoints.ts")

# The closed icon vocabulary. Keep in sync with usage; re-run this script on change.
ICONS = [
    "today", "calendar_month", "checklist", "fitness_center", "restaurant",
    "monitoring", "local_fire_department", "play_arrow", "check_circle",
    "close", "add", "chevron_left", "chevron_right", "expand_more",
    "expand_less", "refresh", "lock", "lightbulb", "offline_bolt",
    "volume_up", "volume_off", "more_horiz", "ios_share", "book", "timer",
    "north_east", "star", "arrow_downward", "arrow_forward",
]


def resolve_codepoints(font: TTFont, names: list[str]) -> dict[str, int]:
    """Map each icon name (a ligature of its letters) to its glyph's PUA codepoint."""
    cmap = font.getBestCmap()  # unicode -> glyphName
    name_to_uni = {gn: cp for cp, gn in cmap.items()}
    char_to_glyph = cmap  # for single chars we still go via unicode

    # Build ligature lookups: (first_glyph, (component_glyphs...)) -> result_glyph
    gsub = font["GSUB"].table
    lig_index = {}
    for lookup in gsub.LookupList.Lookup:
        for sub in lookup.SubTable:
            # LookupType 7 (ExtensionSubst) wraps the real subtable — unwrap it.
            if sub.__class__.__name__ == "ExtensionSubst":
                sub = sub.ExtSubTable
            if sub.__class__.__name__ != "LigatureSubst":
                continue
            for first_glyph, lig_list in sub.ligatures.items():
                for lig in lig_list:
                    key = (first_glyph, tuple(lig.Component))
                    lig_index[key] = lig.LigGlyph

    def glyph_for_char(ch: str):
        return char_to_glyph.get(ord(ch))

    out = {}
    missing = []
    for name in names:
        glyphs = [glyph_for_char(c) for c in name]
        if any(g is None for g in glyphs):
            missing.append(name)
            continue
        key = (glyphs[0], tuple(glyphs[1:]))
        result = lig_index.get(key)
        if result is None:
            missing.append(name)
            continue
        cp = name_to_uni.get(result)
        if cp is None:
            missing.append(name)
            continue
        out[name] = cp
    if missing:
        raise SystemExit(f"Could not resolve codepoints for: {missing}")
    return out


def main():
    if not os.path.exists(SRC_FONT):
        raise SystemExit(f"Source font not found: {SRC_FONT}. Run `npm install` first.")

    font = TTFont(SRC_FONT)
    codepoints = resolve_codepoints(font, ICONS)

    # Subset by the resolved codepoints, keeping variable-font axes intact.
    os.makedirs(os.path.dirname(OUT_FONT), exist_ok=True)
    opts = Options()
    opts.flavor = "woff2"
    opts.layout_features = []       # drop GSUB/GPOS — we render by codepoint, no ligatures
    opts.name_IDs = []              # no name table bloat
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.drop_tables = []           # keep fvar/gvar/STAT so FILL/wght/opsz still work
    ss = Subsetter(options=opts)
    ss.populate(unicodes=list(codepoints.values()))
    ss.subset(font)
    font.flavor = "woff2"
    font.save(OUT_FONT)

    size_kb = os.path.getsize(OUT_FONT) / 1024
    print(f"Wrote {OUT_FONT} ({size_kb:.1f} KB) with {len(codepoints)} icons")

    # Emit the generated TS map + IconName union (single source of truth for the app).
    entries = "\n".join(
        f"  {name}: '\\u{cp:04x}'," for name, cp in codepoints.items()
    )
    ts = (
        "// GENERATED by scripts/subset-icons.py — do not edit by hand.\n"
        "// Maps each icon name to its Material Symbols private-use codepoint.\n"
        "// Re-generate with `npm run gen:icons` after changing the ICONS list.\n\n"
        "export const ICON_CODEPOINTS = {\n"
        f"{entries}\n"
        "} as const;\n\n"
        "export type IconName = keyof typeof ICON_CODEPOINTS;\n"
    )
    with open(OUT_TS, "w") as f:
        f.write(ts)
    print(f"Wrote {OUT_TS}")


if __name__ == "__main__":
    main()
