-- 0005_update_exercise_videos.sql
-- GENERATED by scripts/update-exercise-videos.mjs — do not edit by hand.
-- Swaps in better demo videos for selected exercises. Idempotent: re-running
-- sets the same video_url values. Only the listed slugs are touched.

update exercises as e set video_url = v.video_url
from (values
  ('backsquat', 'https://www.youtube.com/watch?v=R2dMsNhN3DE'),
  ('gobletsquat', 'https://www.youtube.com/watch?v=TzU5zkTEkg8'),
  ('rdl', 'https://www.youtube.com/watch?v=-m45n1_x32E'),
  ('bss', 'https://www.youtube.com/watch?v=uqI3GVwfToU'),
  ('stepup', 'https://www.youtube.com/watch?v=9ZknEYboBOQ'),
  ('packstepup', 'https://www.youtube.com/watch?v=9ZknEYboBOQ'),
  ('slrdl', 'https://www.youtube.com/watch?v=_AKa1yvxD_E'),
  ('latlunge', 'https://www.youtube.com/watch?v=frdrLD_-VAw'),
  ('kbswing', 'https://www.youtube.com/watch?v=wMBWFIn4ddg'),
  ('calfraise', 'https://www.youtube.com/watch?v=GAZzBJIrmB8'),
  ('soleusraise', 'https://www.youtube.com/watch?v=wEbwqWirQNw'),
  ('tib', 'https://www.youtube.com/watch?v=OPEuhclsTUQ'),
  ('ankleiso', 'https://www.youtube.com/watch?v=v_zjz5mOvuY'),
  ('farmer', 'https://www.youtube.com/watch?v=3RKKnZhhelE'),
  ('suitcasemarch', 'https://www.youtube.com/watch?v=MF73qPp1hlM'),
  ('frontrackmarch', 'https://www.youtube.com/watch?v=6lE9Q3QUPsQ'),
  ('stepdown', 'https://www.youtube.com/watch?v=SZXOPRVP1Oc'),
  ('pullup', 'https://www.youtube.com/watch?v=JJp7A277PWw'),
  ('dbbench', 'https://www.youtube.com/watch?v=dGqI0Z5ul4k'),
  ('sarow', 'https://www.youtube.com/watch?v=DMo3HJoawrU'),
  ('trxrow', 'https://www.youtube.com/watch?v=IEky4NL3LLQ'),
  ('pushacc', 'https://www.youtube.com/watch?v=jk4MGqOmjn4'),
  ('pallof', 'https://www.youtube.com/watch?v=f_D0GByfZh0')
) as v(slug, video_url)
where e.slug = v.slug;
